name: passei
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  url_launcher: ^6.3.1
  provider: ^6.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#111A22"
  image: assets/images/logo.png
  android: true
  ios: false
  android_12:
    icon_background_color: "#111A22"
    image: assets/images/logo.png


flutter:  
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/icons/
  
  fonts:
    - family: Ubuntu
      fonts:
        # Thin (100)
        - asset: assets/fonts/Ubuntu-Light.ttf
          weight: 200
          style: normal
        - asset: assets/fonts/Ubuntu-LightItalic.ttf
          weight: 200
          style: italic

        # Regular (400)
        - asset: assets/fonts/Ubuntu-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/Ubuntu-Italic.ttf
          weight: 400
          style: italic

        # Medium (500)
        - asset: assets/fonts/Ubuntu-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/Ubuntu-MediumItalic.ttf
          weight: 500
          style: italic
        
        # Bold (700)
        - asset: assets/fonts/Ubuntu-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/Ubuntu-BoldItalic.ttf
          weight: 700
          style: italic
